import { useState, React } from "react";
import HomeHeader from "./HomeHeader";
import { useNavigate } from "react-router";
import { Card, Container, Button, Form, FormControl, Nav, Navbar, NavDropdown, Row,Col, NavbarBrand } from 'react-bootstrap'
import bgimage from "../images/bg1.jpg";
import "../../src/index.css";

const HotelHomepage = (props) => { 

    const navigate = useNavigate();

    return(
        <div className='container-fluid homeimage' style={{ backgroundImage: `url(${bgimage})`, backgroundRepeat: "no-repeat", backgroundSize: "cover" }}>
            
            <Row><HomeHeader /></Row>
            <div className="homediv">
                <Row style={{marginTop: "15%"}}> 
                    
                    <Col className="homeCard">
                    <Card>
                        <div>
                            <h2>Add rooms</h2>
                            <p>Add new rooms for the customers to book and enjoy their holday vacation.</p>
                            <Button onClick={() => navigate("/addrooms")}>Add room</Button>
                        </div>
                    </Card>
                    </Col>
                    <Col className="homeCard">
                    <Card>
                        <div >
                            <h2>View Customer Feedback</h2>
                            <p>View the feedback reposrt generated by analysing customer feedback in order to improve services.</p>
                            <Button onClick={() => navigate("/viewfeedback")}>View Feedback</Button>
                        </div>
                    </Card>
                    </Col>
                    <Col className="homeCard">
                    <Card >
                        <div >
                            <h2>Visulaization reports</h2>
                            <p>Navigate to this page to visualize differeent reports related to food orderedby customers, rooms booked etc.</p>
                            <Button onClick={() => navigate("/visualize")}>Visualize</Button>
                        </div>
                    </Card>
                    </Col>
                </Row>
                </div>
        
        </div>
    )
}

export default HotelHomepage;