import {React} from "react";

const VisualizeIncomeProfit = () => {
    return(
        <section className="py-5 bg-light">
                <div className="container">
                    <h2>Income-Profit analytics</h2>
                    <p>The below tables and graphs show the income-profit generated by the hotel</p>
                    <div className="row align-items-center" >
                        <iframe
                            width="1000"
                            height="500"
                            src="https://datastudio.google.com/embed/reporting/687d6dcc-a98e-4c4d-bb86-c7fbd5f58eb2/page/tEnnC"
                            frameBorder="1"
                            allowFullScreen >
                        </iframe>
                    </div>
                </div>
            </section>
    );
}

export default VisualizeIncomeProfit;