import { useState, React } from "react";
import HomeHeader from "./HomeHeader";
import { useNavigate } from "react-router";
import { Card, Container, Button, Form, FormControl, Nav, Navbar, NavDropdown, Row,Col, NavbarBrand } from 'react-bootstrap'
import bgimage from "../images/bg1.jpg";
import "../../src/index.css";

const Visualize = (props) => { 

    const navigate = useNavigate();

    return(
        <div className='container-fluid homeimage' style={{ backgroundImage: `url(${bgimage})`, backgroundRepeat: "no-repeat", backgroundSize: "cover" }}>
            
            <Row><HomeHeader /></Row>
            <div className="homediv">
                <Row style={{marginTop: "15%"}}> 
                    
                    <Col className="homeCard">
                    <Card>
                        <div>
                            <h2>Visualize RoomBooking</h2>
                            <p>Click the button to visualize room bookings done by customers.</p>
                            <Button onClick={() => navigate("/visualizeroom")}>Visualize</Button>
                        </div>
                    </Card>
                    </Col>
                    <Col className="homeCard">
                    <Card>
                        <div >
                            <h2>Visualize Income Report</h2>
                            <p>Click the button to visualize income and profits generated by the hotel.</p>
                            <Button onClick={() => navigate("/visualizeincomeprofit")}>Visualize</Button>
                        </div>
                    </Card>
                    </Col>
                    <Col className="homeCard">
                    <Card >
                        <div >
                            <h2>Visualize Food Orders</h2>
                            <p>Click the button to visualize food order requests by the customers.</p>
                            <Button onClick={() => navigate("/visualizefoodorder")}>Visualize</Button>
                        </div>
                    </Card>
                    </Col>
                </Row>
                </div>
        
        </div>
    )
}

export default Visualize;